name: Merge Bot

on:
  pull_request:
    types: [labeled, unlabeled, review_request_removed]
  pull_request_review:

jobs:
  merge:
    runs-on: ubuntu-latest
    name: Merge
    steps:
    - name: Integration check
      uses: squalrus/merge-bot@v0.2.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        test: true
        labels: ready, merge
        blocking-labels: do not merge
